### ISSUE TITLE
After connecting plugin to app, returns to a blank screen

### ISSUE THREAD

**Issue by chrisjpatty** [Automattic/facebook-instant-articles-wp#336]
This is driving me crazy. I saw somebody else had this problem and it was never resolved. Every time I connect it to my app it just returns with a blank page instead of a dropdown where I can pick my pages. Help please!

# Steps required to reproduce the problem

1. Installed and activated the plugin.
2. Input my app id and secret
3. connected the app to my account and redirected back.

# Expected Result

* A list of my pages to pick from

# Actual Result

* A nearly blank plugin screen. See this screenshot: 
![image](https://cloud.githubusercontent.com/assets/14916515/16254588/a915e2fe-37fe-11e6-98fb-ce7e754fe552.png)

---

** Version Info **

* Plugin version: 
* WordPress version: 4.5.3
* PHP version: Unknown

**Comment by jo4nny8** [comment]
I have exactly the same issue.  Ive completely deleted the plugin, all options from wordpress etc and done a fresh install but its exactly the same.

**Comment by krispy1298** [comment]
in my scenario, I'm getting this error in the system logs:

```
PHP Fatal error:  Uncaught exception 'Facebook\\Exceptions\\FacebookSDKException' with message 'Graph API returned an error: Application does not have permission for this action' in /nas/content/live/patagonia/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Client/Helper.php:94\nStack trace:\n#0 /nas/content/live/patagonia/wp-content/plugins/fb-instant-articles/settings/template-settings-wizard.php(147): Facebook\\InstantArticles\\Client\\Helper->getPagesAndTokens(Object(Facebook\\Authentication\\AccessToken))\n#1 /nas/content/live/patagonia/wp-content/plugins/fb-instant-articles/settings/template-settings.php(16): include('/nas/content/li...')\n#2 /nas/content/live/patagonia/wp-content/plugins/fb-instant-articles/settings/class-instant-articles-settings.php(144): include('/nas/content/li...')\n#3 [internal function]: Instant_Articles_Settings::render_settings_page('')\n#4 /nas/content/live/patagonia/wp-includes/plugin.php(525): call_user_func_array(Array, Array)\n#5 /nas in /nas/content/live/patagonia/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Client/Helper.php on line 94
```

Even though the docs for FB Apps states (specifically for the `pages_manage_instant_articles` permission):

> you do not need to submit for review as long as all those for whom you want to publish are listed in the Roles section of your app dashboard.

I am an admin on both the App and Page I am using for my set up.

Not sure if this is the exact thing going on for the others in this thread, but hopefully it can help.

**Comment by diegoquinteiro** [comment]
Hi, thanks for reporting! This was a bug on the Instant Articles API and we fixed it this morning. Please reopen if you still have issues.

Thank you!

**Comment by jo4nny8** [comment]
How do we fix it?  I'm not showing an update through Wordpress. Do I need to download it directly from here?

**Comment by diegoquinteiro** [comment]
@jo4nny8 sorry, I wasn't clear. The issue is not on the plugin, it was on Facebook servers itself. It was fixed as of this morning. Can you simply retry going through the flow?

Thanks!

**Comment by jo4nny8** [comment]
Unfortunately still no joy.

Should I delete the plugin and start again?

**Comment by jo4nny8** [comment]
![image](https://cloud.githubusercontent.com/assets/6171316/16318233/1b1c42de-3986-11e6-8d99-f47be0680238.png)

**Comment by benelang** [comment]
I also run into this problem. I doublechecked the permissions for the app in my facebook permission settings. I reinstalled the plugin which did not solve the problem.

**Comment by everton-rosario** [comment]
@benelang @jo4nny8 @krispy1298 @chrisjpatty 
Make sure you all are using the version 3.0.1 of the "Facebook Instant Articles WordPress plugin" and with the 1.3.0 of "Facebook Instant Articles PHP SDK".

Once you have all this updated:
- Make sure your app uses the same domain URL of your page
- Certify you've set your app to use this permission: https://developers.facebook.com/docs/facebook-login/permissions#reference-pages_manage_instant_articles
- Certify the user that is logging in the plugin have admin role to the Facebook Page. (In case the user isn't admin, the page wont be listed.

**Comment by jo4nny8** [comment]
I managed to sort this a couple of weeks ago.

I 'dropped back' to an old version (2.1 wish i think) and simply uploaded it to my plugins folder overwriting the latest version.

Once i refreshed my page in the admin it worked and i was able to login to Facebook etc.

Once i had done that, i simply updated the plugin and its all been fine since.

**Comment by everton-rosario** [comment]
Thanks for the feedback @jo4nny8

**Comment by benelang** [comment]
For me it works as we enabled curl_exec for php. Would be great if the plugin wouldnt require curl_exec due to security reasons

**Comment by everton-rosario** [comment]
The curl_exec comes from the Facebook main SDK (https://github.com/facebook/facebook-php-sdk-v4)
We still have nothing to do to avoid this and still no plans to have this kind of feature implemented.

If you override these functions, maybe you can have this fixed. If you find something to work around, send us the PR.

Thanks for flagging this @benelang
